version: "3.8"

services:
  trading-bot:
    build: .
    container_name: node-app
    ports:
      - "6000:6000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/trading-bot
      - NODE_ENV=dev
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app  
      - /usr/src/app/node_modules 

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./utils/initdb.js:/docker-entrypoint-initdb.d/initdb.js  # Update the path here
      - ./utils/trades.json:/docker-entrypoint-initdb.d/trades.json

volumes:
  mongo-data: